### ISSUE TITLE
channels going back in time

### ISSUE THREAD

**Issue by disassembler** [NixOS/nixos-channel-scripts#14]
@BlessJah reported on IRC yesterday that 17.09 went back in time with a channel update. He wrote a script he runs daily to check this now: http://dpaste.com/3DYQTAD

@grahamc and I confirmed that our channels had downgraded to. @grahamc explained "the channel is based on the newest build of hydra which has completely finished building. if you restart jobs, the
 newest to completely finish goes back to an older build. the channel update tool has code to guard against going back in time, but it seems to be broken"

@romildo on IRC reported the same thing happening for 18.03pre (unstable) today.

**Comment by BlessJah** [comment]
@BlessJah have reported this on other occasions as well:
```
2017/08/17 1411< BlessJah> was there downgrade of nixos-17.03 channel? It seems it went down from 17.03.1700.51a83266d1 to 17.03.1665.055e5c3578
```
On one occasion @BlessJah have noticed that *small* channel is not advancing while regular one is:
```
2017/09/21 1334< BlessJah> hyper_ch: 17.03-small was stuck or downgraded to 17.03.1817.694529e45d over week ago, it just moved today
2017/09/21 1335< hyper_ch> only one week no updates? oO
2017/09/21 1336< BlessJah> Keep in mind we're talking about 17.03-small. Regular 17.03 was updated every other day.
```

The script @BlessJah wrote is to let him easily check if upgrades are awaiting, but it is as good at detecting downgrades.

**Comment by domenkozar** [comment]
See #22
