### ISSUE TITLE
adb missing from command-not-found

### ISSUE THREAD

**Issue by timokau** [NixOS/nixos-channel-scripts#16]
I'm not sure how exactly the `programs.sqlite` database is generated or if this is even a bug. But it was surprising to me, so I thought I'd bring it up.

`command-not-found adb` doesn't find a package for `adb`, even though `android-platform-tools` has a file `bin/adb` which is a symlink to `platform-tools/adb`.

**Comment by vcunat** [comment]
My tip is on `androidsdk.meta.hydraPlatforms == []`, so it's not built on the farm and thus can't even find what it contains.

**Comment by timokau** [comment]
So this is probably a license issue and can't easily be fixed?

**Comment by vcunat** [comment]
No, `hydraPlatforms` isn't used for licenses, as we have an extra field for that.  It's typically to save farm's resources; in this case probably because taking too much space.

**Comment by timokau** [comment]
Okay, if it is expected behaviour and there is a reason for that this can probably be closed.
Thanks for clarifying.
