### ISSUE TITLE
mirror-channel.pl: Upload binary cache in topologically sorted order

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixos-channel-scripts#2]
Otherwise, if we upload a path before all its dependencies are uploaded, users can get a "don't know how to build these paths" warning from Nix.

https://github.com/NixOS/nix/issues/765

**Comment by edolstra** [comment]
Closing, no longer applicable.

**Comment by copumpkin** [comment]
@edolstra does that mean https://github.com/NixOS/nix/issues/765 is no longer applicable either, and can be closed?

**Comment by edolstra** [comment]
@copumpkin Not entirely. I think you can still get that error due to negative caching of binary cache lookups.
