### ISSUE TITLE
Revive command-not-found support

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixos-channel-scripts#4]
We no longer generate `programs.sqlite` because that would require downloading all packages from cache.nixos.org. Need a solution. E.g. Hydra could upload a content listing of every NAR to the cache, which `generate-programs-index.pl` could download (with some local caching).

**Comment by domenkozar** [comment]
I'm thinking how `command-not-found` could also work for custom hydra installations. Maybe we could use multiple outputs to generate a list of installed files and `command-not-found` would depend on that output for all `pkgs`?

**Comment by domenkozar** [comment]
It would need to be pluggable, so maybe that's not ideal as it would have a different hash on hydra vs normal installation that wouldn't generate the lists.

**Comment by vcunat** [comment]
It would be nice if the hook worked in 16.03, but we should at least put it into release notes if it won't. (funnily enough, we have an item in there improving the hook :)

**Comment by vcunat** [comment]
I hoped the file list in a NAR would be decodable from a very short prefix of the NAR, but that seems not to be the case.

As you suggest, it currently seems easiest to:
- Create *.narlist next to *.narinfo when uploading to the cache; perhaps it might include listing of all files, as the extra size should be bearable at this point. (And we might compress this file; it should compress well.)
- After all is finished and release should happen, download all \*.narlist and generate file database(s) (at least the one for bin/*).
- Optionally, we might add a web service querying those databases.

**Comment by layus** [comment]
While we are designing a new system, it may be a nice bonus to make it general enough to support other use cases.
I am thinking in particular to LaTeX wrappers able to download the right packages for a given document. That would be very useful for per-document nix-shell environments now that we have a fully modular tex distribution.

**Comment by vcunat** [comment]
In case of TeX the situation is easier due to upstream providing listings of all package contents. ftp://tug.ctan.org/pub/tex/historic/systems/texlive/2015/tlnet-final/tlpkg/texlive.tlpdb.xz

**Comment by aloiscochard** [comment]
Is there a workaround for this, so it could fail temporarily silently?

The error is very verbose when using `fish`.

**Comment by domenkozar** [comment]
I've disabled it for now: https://github.com/NixOS/nixpkgs/commit/2a3c0ca3d5ab0fe9aaa312199b3cad5bc9a01934

**Comment by chris-martin** [comment]
Thanks, it was getting embarrassing while I'm trying to show nix off :smile:

**Comment by FRidh** [comment]
> While we are designing a new system, it may be a nice bonus to make it general enough to support other use cases.

There was also talk of some kind of dependency solver for precompiled binaries. That could also benefit from such database.

**Comment by chris-martin** [comment]
Would it be absurd to suggest explicitly passing a list of expected `bin/` outputs to `mkDerivation`? It might be nice to have that anyway so the build process can do a sanity check to verify that bin contains the right things.

**Comment by domenkozar** [comment]
@edolstra if you implement hydra uploading file contents to S3, I'm willing to take care of the rest.

**Comment by bjornfor** [comment]
My current workaround: use a Ubuntu VM to figure out command -> package-name mapping... Should I laugh or cry? :-)

**Comment by Myrl** [comment]
@bjornfor I have an outdated VPS just for this.

**Comment by copumpkin** [comment]
https://github.com/NixOS/nixpkgs/commit/dc7e32e618bbc962ddbdd03b596966a1deac5fb4

**Comment by domenkozar** [comment]
Thanks!!

**Comment by puffnfresh** [comment]
:fireworks:

**Comment by bjornfor** [comment]
Yay! Thank you, @edolstra!

**Comment by canndrew** [comment]
So... how do I get this working? If I run `command-not-found` I get:

```
DBI connect('dbname=/nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite','',...) failed: unable to open database file at /run/current-system/sw/bin/command-not-found line 13.
cannot open database `/nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite' at /run/current-system/sw/bin/command-not-found line 13.
```

Is there a way to fix it on an existing NixOS install?

**Comment by vcunat** [comment]
@canndrew: apparently your channel isn't new enough; try `sudo nix-channel --update`.

**Comment by canndrew** [comment]
Nope, that didn't change anything. I have `nix.nixPath` set to point at my own local clone of nixpkgs but that is currently up-to-date with nixpkgs-channels/nixos-unstable. Also I only installed NixOS a couple of weeks ago, after this bug was closed.

Any more ideas?

**Comment by chris-martin** [comment]
I also haven't seen this working yet. I don't use `nix-channel` at all anymore. Is that a requirement?

**Comment by edolstra** [comment]
Yeah, you have to use `nix-channel` because `command-not-found` looks specifically in `/nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite`.

**Comment by domenkozar** [comment]
Note that generation was disabled again, please comment on https://github.com/NixOS/nixos-channel-scripts/issues/9
