### ISSUE TITLE
Publish channels to S3

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixos-channel-scripts#7]
I see three good reasons to do this:

- S3+cloudfront have been extremely stable (not that nixos.org was down for any long time) and they're decentralized, leaving last single point of failure on the side when using NixOS
- `nix-channel --update` would not redownload channel on each invocations since [it would respect the etag header](https://github.com/NixOS/nix/issues/888#issuecomment-238380072)
- we won't need to recycle channels to free disk space, so declarative `$NIX_PATH` [wouldn't fail anymore](https://github.com/NixOS/nixops/issues/405) since upstream `nixpkgs.tar.xz` is missing

Would this add much to the costs?

cc @edolstra

**Comment by edolstra** [comment]
No, the only cost is having to rewrite the channel scripts.
